language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-firefox-extension' ]; then cd .. && eval "mv $currentfolder generator-firefox-extension" && cd generator-firefox-extension; fi
